// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/list-clients.ts
import { createClient } from "npm:@supabase/supabase-js@^2.97.0";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^3.25.76";
function db(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_clients_default = defineTool({
  name: "list_clients",
  title: "List clients",
  description: "List clients (customers/brands) the signed-in user has access to in CorePlan.",
  inputSchema: {
    search: z.string().optional().describe("Optional name substring filter."),
    limit: z.number().int().min(1).max(200).optional().describe("Max rows to return (default 50).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ search, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    let q = db(ctx).from("clients").select("id,name,currency,annual_budget,created_at").is("deleted_at", null).order("name").limit(limit ?? 50);
    if (search) q = q.ilike("name", `%${search}%`);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return { content: [{ type: "text", text: JSON.stringify(data) }], structuredContent: { clients: data ?? [] } };
  }
});

// src/lib/mcp/tools/list-activities.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.97.0";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^3.25.76";
function db2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_activities_default = defineTool2({
  name: "list_activities",
  title: "List activities",
  description: "List CorePlan marketing activities the signed-in user can see. Optionally filter by client, status, or date range.",
  inputSchema: {
    client_id: z2.string().uuid().optional().describe("Filter by client UUID."),
    status: z2.enum(["planned", "in_progress", "completed", "cancelled"]).optional(),
    start_from: z2.string().optional().describe("ISO date; include activities starting on or after this date."),
    start_to: z2.string().optional().describe("ISO date; include activities starting on or before this date."),
    limit: z2.number().int().min(1).max(500).optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    let q = db2(ctx).from("activities").select("id,name,client_id,status,channel,campaign_type,start_date,end_date,price,note").is("deleted_at", null).order("start_date", { ascending: false }).limit(input.limit ?? 100);
    if (input.client_id) q = q.eq("client_id", input.client_id);
    if (input.status) q = q.eq("status", input.status);
    if (input.start_from) q = q.gte("start_date", input.start_from);
    if (input.start_to) q = q.lte("start_date", input.start_to);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return { content: [{ type: "text", text: JSON.stringify(data) }], structuredContent: { activities: data ?? [] } };
  }
});

// src/lib/mcp/tools/list-products.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.97.0";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z3 } from "npm:zod@^3.25.76";
function db3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_products_default = defineTool3({
  name: "list_products",
  title: "List products",
  description: "List products from the CorePlan catalog accessible to the signed-in user.",
  inputSchema: {
    search: z3.string().optional().describe("Optional name substring filter."),
    category: z3.string().optional(),
    client_id: z3.string().uuid().optional(),
    limit: z3.number().int().min(1).max(500).optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    let q = db3(ctx).from("products").select("id,name,category,subcategory,brand,ean,client_id").is("deleted_at", null).order("name").limit(input.limit ?? 100);
    if (input.search) q = q.ilike("name", `%${input.search}%`);
    if (input.category) q = q.eq("category", input.category);
    if (input.client_id) q = q.eq("client_id", input.client_id);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return { content: [{ type: "text", text: JSON.stringify(data) }], structuredContent: { products: data ?? [] } };
  }
});

// src/lib/mcp/tools/create-activity.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.97.0";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z4 } from "npm:zod@^3.25.76";
function db4(ctx) {
  return createClient4(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var create_activity_default = defineTool4({
  name: "create_activity",
  title: "Create activity",
  description: "Create a new marketing activity in CorePlan for a given client.",
  inputSchema: {
    name: z4.string().trim().min(1).describe("Activity name."),
    client_id: z4.string().uuid().describe("Target client UUID."),
    start_date: z4.string().describe("ISO start date (YYYY-MM-DD)."),
    end_date: z4.string().describe("ISO end date (YYYY-MM-DD); must be >= start_date."),
    price: z4.number().min(0).optional().describe("Budget/price for the activity (>= 0)."),
    channel: z4.string().optional(),
    campaign_type: z4.string().optional(),
    status: z4.enum(["planned", "in_progress", "completed", "cancelled"]).optional(),
    note: z4.string().optional()
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    if (input.end_date < input.start_date) {
      return { content: [{ type: "text", text: "end_date must be on or after start_date" }], isError: true };
    }
    const { data, error } = await db4(ctx).from("activities").insert({
      user_id: ctx.getUserId(),
      name: input.name,
      client_id: input.client_id,
      start_date: input.start_date,
      end_date: input.end_date,
      price: input.price ?? 0,
      channel: input.channel ?? "",
      campaign_type: input.campaign_type ?? "",
      status: input.status ?? "planned",
      note: input.note
    }).select().single();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return { content: [{ type: "text", text: `Activity created: ${data.id}` }], structuredContent: { activity: data } };
  }
});

// src/lib/mcp/index.ts
var projectRef = "aswmmhxyqafqsvnnspqj";
var mcp_default = defineMcp({
  name: "coreplan-mcp",
  title: "CorePlan",
  version: "0.1.0",
  instructions: "Tools for CorePlan \u2014 a marketing media-plan platform. Use `list_clients`, `list_activities`, and `list_products` to read the signed-in user's workspace, and `create_activity` to add a new activity for a client.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_clients_default, list_activities_default, list_products_default, create_activity_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
